# Generated by Django 4.2 on 2023-04-30 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attenuation', '0003_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contact',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
