# Generated by Django 4.2 on 2023-04-30 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attenuation', '0004_contact_done_contact_summary'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instock', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('sold', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='attenuation.product')),
            ],
        ),
    ]
